## Welcome to the Hands On Notebook for Day 3

Target: 
- Students memahami cara melakukan beberapa Operations di Python (Arithmetic, Assignment, Comparison, Logical, Identity, Membership dan Bitwise Operators)
- Students memahami perbedaan Tipe Data di Python yaitu Numerical dan Categorical Data serta Object
- Students memahami perbedaan Data Structure di Python antara lain : Numpy Array, List, Tuple, Dictionary dan Set

### Part 1: Operations in Python

Apa itu operations? Layaknya operasi matematika, maka `operations` di Python dapat diartikan sebagai komputasi. Operations yang paling dasar adalah *****arithmetic*****, yaitu perhitungan matematis dasar (tambah, kurang, kali, bagi, kurung, dll).

In [1]:
1 + 1

2

In [2]:
5 - 2 * 3

-1

In [3]:
(5 - 2) * 3

9

Operations kedua yang kita bahas adalah *****assignment*****, yaitu menyatakan suatu variabel dengan suatu nilai.

Di bangku sekolah, mungkin kita sering berurusan dengan "Misalkan x = 3". Hal tersebut adalah sebuah contoh dari sebuah *****assignment*****.

In [4]:
print(x)

NameError: name 'x' is not defined

In [5]:
x = 3
print(x)

3


Misal kita ingin mengubah nilai `x` menjadi 4. Apakah bisa? Tentu bisa. 

In [6]:
x = 4
print(x)

4


Selanjutnya, kita ingin mengubah nilai `x` menjadi dua kali dari dirinya sendiri. Bagaimana caranya?

In [7]:
x = 2 * x
print(x)

8


Langkah di atas berarti:
1. Ambil variabel x
2. Kalikan 2
3. Hasil dari perkalian tersebut, kembali disimpan dengan nama 'x'

Operations selanjutnya adalah *****Logical*****. Bahasa sederhananya, mengecek kebenaran dari suatu pernyataan. 
Operations *****Logical***** sendiri terdiri dari beberapa 'jenis':
- *****Comparison*****
- *****Identity*****
- *****Membership*****

****Comparison**** adalah membandingkan apakah suatu nilai lebih besar atau lebih kecil (atau sama dengan) nilai lain.

In [10]:
x = 5
y = 3

x > y

True

In [11]:
x < y

False

In [12]:
x + y == 8

True

In [13]:
x + y - 3 >= 0

True

***Identity*** memeriksa identitas suatu variabel dengan `is` atau `is not`

In [15]:
type(5) is int

True

In [16]:
print(x)
print(y)

5
3


In [17]:
x is y

False

In [18]:
x is not y

True

In [19]:
type(y) is str

False

In [20]:
type(x) is not list

True

***Membership*** memeriksa apakah suatu variabel merupakan anggota variabel lain (variabel lain ini biasanya berupa sebuah list, himpunan, dst)

In [21]:
daftar_bilangan = [1,2,3,4,5]
print('Apakah 5 dalam daftar bilangan? ', 5 in daftar_bilangan)
print('Apakah 10 dalam daftar bilangan? ', 10 in daftar_bilangan)

Apakah 5 dalam daftar bilangan?  True
Apakah 10 dalam daftar bilangan?  False


***Bitwise*** operator adalah operator untuk menyatakan `dan`, `atau`, dll. Untuk lengkapnya, silakan lihat di https://realpython.com/python-bitwise-operators/. 

In [22]:
a = 5
b = 3

In [39]:
### a atau b lebih besar dari 4
(a > 4) | (b > 4)

True

In [40]:
### a dan b lebih besar dari 4
(a > 4) & (b > 4)

False

In [41]:
### either a or b is greater than 4, but not both (XOR / Exclusive OR)
(a > 4) ^ (b > 4)

True

In [43]:
### either a or b is greater than 2, but not both (XOR / Exclusive OR)
(a > 2) ^ (b > 2)

False

Untuk mengerti `left shift` dan `right shift` pada bitwise operators, silakan baca https://blog.finxter.com/python-bitwise-left-shift/. 

### Part 2: Data Types in Python

Basic data types in Python are:
- string (text)
- integer 
- float (decimals)
- bool (true or false)

In [48]:
### Contoh string
x = 'teks'
type(x)

str

In [49]:
### Contoh int
x = 1
type(x)

int

In [50]:
### Contoh float
x = 1.0
type(x)

float

In [52]:
### Contoh bool
x = 1==1
type(x)

bool

Namun, dalam `pandas`, terdapat beberapa data types yang lebih spesifik sehingga membuat pengolahan data lebih mudah.

- Sebuah kolom yang terdiri dari nilai-nilai yang berhubungan dengan waktu disebut memiliki tipe data `datetime`
- Sebuah kolom yang berisi durasi waktu (45 menit, 5 jam), disebut memiliki time data `timedelta`
- Sebuah kolom yang memiliki lebih dari 1 tipe data disebut memiliki tipe data `object`
- Sebuah kolom `str` dapat dijadikan tipe `categorical` untuk keperluan `machine learning` (nanti akan dibahas)

In [62]:
import pandas as pd

df = pd.DataFrame({
    'tanggal_mulai':['2021-01-01', '2021-01-02', '2021-01-03'],
    'tanggal_selesai':['2022-02-02', '2021-02-02', '2021-03-03'],
    'kode_pekerjaan':[1,2,'tiga'],
    'jenis_kelas':['class-1', 'class-2', 'class-1']
})

df['tanggal_mulai'] = pd.to_datetime(df['tanggal_mulai'])
df['tanggal_selesai'] = pd.to_datetime(df['tanggal_selesai'])
df['durasi'] = df['tanggal_selesai'] - df['tanggal_mulai']
df['jenis_kelas'] = df['jenis_kelas'].astype('category')

In [64]:
df

tanggal_mulai tanggal_selesai kode_pekerjaan jenis_kelas   durasi
0    2021-01-01      2022-02-02              1     class-1 397 days
1    2021-01-02      2021-02-02              2     class-2  31 days
2    2021-01-03      2021-03-03           tiga     class-1  59 days

In [63]:
df.dtypes

tanggal_mulai       datetime64[ns]
tanggal_selesai     datetime64[ns]
kode_pekerjaan              object
jenis_kelas               category
durasi             timedelta64[ns]
dtype: object

### Part 3: Data Structures in Python

Struktur data yang penting dikenali oleh pemula Python adalah:
- list
- numpy array
- tuple
- dictionary
- set

List adalah daftar terurut. Kita bisa memasukkan apa pun ke dalam list dan list akan mengurutkannya sesuai index. 

In [67]:
### list, which is used to store other objects and give them order (urutan berpengaruh)
list_contoh = [1,2,3,4,5,6]

List di atas beranggotakan bilangan-bilangan bulat

In [68]:
list_contoh_2 = ['a', 'b', 'c', 'd', 'e']

List di atas beranggotakan `string`. 

In [69]:
list_contoh_2[5]

IndexError: list index out of range

In [70]:
list_contoh[0]

1

In [71]:
list_contoh[1]

2

Dan kita bisa 'memanggil' anggota-anggota dari list itu menurut INDEX nya (posisi).

Selain itu, kita juga bisa menambahkan sesuatu ke dalam list yang telah dibuat

In [72]:
list_contoh.append(8)

In [73]:
list_contoh

[1, 2, 3, 4, 5, 6, 8]

Kita menambahkan angka '8' untuk dimasukkan ke dalam list_contoh. 

Perbedaan `numpy array` dan `list` adalah `numpy array` lebih difokuskan untuk operasi matematika.

In [75]:
import numpy as np
array_contoh = np.array([1,2,3,4,5,6,7,8])

In [76]:
array_contoh / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [77]:
list_contoh / 2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [80]:
matriks_contoh = np.array([[1,2,3],[2,3,4],[3,4,5]])
matriks_contoh

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [81]:
np.linalg.inv(matriks_contoh)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

Tuple adalah sejenis `list` namun tidak dapat ditambah / dikurangi

In [82]:
tuple_contoh = (1,2,3,4,5,6,7,8)

In [83]:
tuple_contoh.append(10)

AttributeError: 'tuple' object has no attribute 'append'

Mengapa terkadang tuple digunakan? Karena tuple lebih memory-efficient daripada list

In [84]:
from sys import getsizeof

In [86]:
getsizeof(list_contoh)

152

In [87]:
getsizeof(tuple_contoh)

104

Jadi, jika kita tidak membutuhkan fungsi menambahkan anggota baru pada daftar kita, maka sebaiknya gunakan saja `tuple` daripada `list`. 

Set adalah himpunan - tidak boleh ada anggota duplikat dalam himpunan, tapi tidak ada index/urutan.

In [1]:
set_contoh = set(['k','a','m','p','u','s','m','e','r','d','e','k','a'])

In [2]:
set_contoh

{'a', 'd', 'e', 'k', 'm', 'p', 'r', 's', 'u'}

In [6]:
type(set_contoh)

set

In [10]:
set_x = {1,2,3}
set_y = {3,4,5}
set_x.intersection(set_y)

{3}

In [11]:
set_x.union(set_y)

{1, 2, 3, 4, 5}

Last but not least, dictionary dikenal di bahasa pemrograman lain sebagai `hash map`, yang memudahkan kita melakukan pemetaan. Langsung saja kita lihat contohnya sebagai berikut:

In [96]:
harga_satuan = {
    'biru':5000,
    'merah':4500,
    'hijau':4000,
    'kuning':4250
}


df = pd.DataFrame({
    'warna':['biru', 'merah', 'merah', 'biru', 'biru', 'kuning', 'hijau', 'kuning'],
    'terjual':[2,3,3,4,5,3,4,5]
})

df

warna  terjual
0    biru        2
1   merah        3
2   merah        3
3    biru        4
4    biru        5
5  kuning        3
6   hijau        4
7  kuning        5

In [97]:
df['harga_per_satuan'] = df['warna'].map(harga_satuan)
df['total_pendapatan'] = df['terjual'] * df['harga_per_satuan']

In [98]:
df

warna  terjual  harga_per_satuan  total_pendapatan
0    biru        2              5000             10000
1   merah        3              4500             13500
2   merah        3              4500             13500
3    biru        4              5000             20000
4    biru        5              5000             25000
5  kuning        3              4250             12750
6   hijau        4              4000             16000
7  kuning        5              4250             21250

In [12]:
import pandas as pd

In [14]:
satuan = {
    'biru':5000,
    'merah':4500,
    'hijau':4000,
    'kuning':4250,
    'hitam':6000
}


df = pd.DataFrame({
    'warna':['biru', 'merah', 'merah', 'hitam', 'biru', 'biru', 'kuning', 'hijau', 'hitam', 'kuning'],
    'terjual':[2,3,3,4,5,3,4,5,4,2]
})

df

warna  terjual
0    biru        2
1   merah        3
2   merah        3
3   hitam        4
4    biru        5
5    biru        3
6  kuning        4
7   hijau        5
8   hitam        4
9  kuning        2

In [17]:
df['harga_per_satuan'] = df['warna'].map(satuan)
df['total_pendapatan'] = df['terjual'] * df['harga_per_satuan']

In [18]:
df

warna  terjual  harga_per_satuan  total_pendapatan
0    biru        2              5000             10000
1   merah        3              4500             13500
2   merah        3              4500             13500
3   hitam        4              6000             24000
4    biru        5              5000             25000
5    biru        3              5000             15000
6  kuning        4              4250             17000
7   hijau        5              4000             20000
8   hitam        4              6000             24000
9  kuning        2              4250              8500